# Copyright (c) 2016, Intel Corporation
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# This is the main cmake file of the DebugAgent project


# Contains windows-specific installation

# installing PFW shared libraries and dependencies
install(FILES
    $<TARGET_FILE:ParameterFramework::parameter>
    $<TARGET_FILE:ParameterFramework::remote-processor>
    ${PFW_INSTALL_DIR}/bin/libxml2.dll
    DESTINATION bin)

#installing Root PFW configuration files
install(DIRECTORY resources/parameter-framework DESTINATION .)

# installing batch files to run the DBGA with specific command-line parameters
install(FILES
    "resources/scripts/Windows/DebugAgent_d.bat"
    DESTINATION bin CONFIGURATIONS Debug RENAME DebugAgent.bat)
install(FILES
    "resources/scripts/Windows/DebugAgent.bat"
    DESTINATION bin CONFIGURATIONS Release)
create_shortcut(bin/DebugAgent.bat "Run Debug Agent")

# Creating the directory that will receive xml structure files generated by the fdk tool
install(DIRECTORY DESTINATION "parameter-framework/cavs")

# Installing a batch file that opens the cavs xml directory
install(FILES resources/scripts/Windows/OpenCAVSFolder.bat DESTINATION bin)
create_shortcut(bin/OpenCAVSFolder.bat "Open DBGA Config")

# Installing README file and creating shortcut
install(FILES "resources/docs/README.html" DESTINATION ".")
create_shortcut(README.html "DBGA README")

# including windows runtime libraries
#
# Note 1: there are two ways to deploy visual studio runtime libraries:
# - "application local" way: libraries are deployed by the application installer
# - "vcredist package" way: libraries are deployed by a microsoft dedicated installer
#
# Currently the DBGA uses the "application local" way to simplify user installation
# (only one installer is needed), but it is not a good solution anymore since visual studio 2015,
# because this release requires approx. 50 runtime libraries!
# @todo: use the "vcredist package" way instead of "application local" way.
#
# Note 2: the "application local" way can be achieved using the cmake module
# "InstallRequiredSystemLibraries", but it has been chosen to not use it because:
# - currently it doesn't handle properly new visual studio "universal" runtime libraries
#   (see https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/)
# - this module is not suitable to select runtime library configuration (debug/release)
#   according to the installer configuration
# - this module retrieves runtime libraries from the builder host, which may have been modified.
#   It is safer to retrieve them from the source control.

set(MSVC_DIR "${PROJECT_SOURCE_DIR}/external/msvc_2015")
file(GLOB COMMON_DLL "${MSVC_DIR}/common/*.dll")
file(GLOB RELEASE_DLL "${MSVC_DIR}/release/*.dll")
file(GLOB DEBUG_DLL "${MSVC_DIR}/debug/*.dll")

install(FILES ${COMMON_DLL} DESTINATION bin)
install(FILES ${RELEASE_DLL} DESTINATION bin CONFIGURATIONS Release)
install(FILES ${DEBUG_DLL} DESTINATION bin CONFIGURATIONS Debug)
